#!/usr/bin/env Rscript

# ============================================================
# 03_graph_sv_summary_plots.R
#
# Purpose:
#   Read a graph-based structural variant genotype table that
#   has already been filtered to retain SVs >= 50 bp, infer
#   SV type and approximate SV length from REF and ALT allele
#   lengths, and generate:
#     1. Per-sample SV count plot
#     2. SV length distribution plot
#     3. Global allele frequency (AF) distribution
#     4. Global minor allele frequency (MAF) distribution
#
# Input:
#   graph_sv_table.tsv
#
# Output:
#   Number_of_SVs_per_sample.pdf/png
#   SV_length_distribution.pdf/png
#   SV_allele_frequency_distribution.pdf/png
#   SV_minor_allele_frequency_distribution.pdf/png
#
# Input preparation:
#   bcftools query -H -f '%CHROM\t%POS\t%ID\t%REF\t%ALT[\t%GT]\n' \
#     salix_graph_75samples.merged.PASS.SV50.vcf.gz > graph_sv_table.tsv
#
# Notes:
#   - The input VCF has already been filtered to retain variants
#     of at least 50 bp.
#   - Because the graph-based VCF does not contain standard
#     SVTYPE/SVLEN INFO fields, SV type and length are inferred
#     from REF and ALT allele lengths.
# ============================================================

suppressPackageStartupMessages({
  library(tidyverse)
})

# ------------------------------------------------------------
# Input file
# ------------------------------------------------------------
sv_table_file <- "graph_sv_table.tsv"

# ------------------------------------------------------------
# Step 1: Read graph-based SV genotype table
# Expected columns:
#   CHROM, POS, ID, REF, ALT, sample genotype columns...
# ------------------------------------------------------------
sv_raw <- read_tsv(sv_table_file, show_col_types = FALSE)

# Clean sample column names generated by bcftools query
colnames(sv_raw) <- colnames(sv_raw) |>
  gsub("^#\\[[0-9]+\\]", "", x = _) |>
  gsub("^\\[[0-9]+\\]", "", x = _) |>
  gsub(":GT$", "", x = _)

# ------------------------------------------------------------
# Step 2: Infer approximate SV length and SV type from REF/ALT
# lengths
#
# Since the graph-based input was already filtered to >= 50 bp
# at the VCF level, no additional size filtering is applied here.
# ------------------------------------------------------------
sv_annotated <- sv_raw %>%
  mutate(
    ref_len = nchar(REF),
    alt_len = nchar(ALT),
    SVLEN = alt_len - ref_len,
    SVTYPE = case_when(
      SVLEN > 0 ~ "INS",
      SVLEN < 0 ~ "DEL",
      TRUE ~ "OTHER"
    )
  )

cat("Number of input variants:", nrow(sv_raw), "\n")
cat("Number of annotated variants:", nrow(sv_annotated), "\n")
cat("SV type counts:\n")
print(table(sv_annotated$SVTYPE, useNA = "ifany"))
cat("Summary of absolute inferred SV length:\n")
print(summary(abs(sv_annotated$SVLEN)))

# ------------------------------------------------------------
# Step 3: Identify sample genotype columns
# Assumes first 5 columns are:
#   CHROM, POS, ID, REF, ALT
# ------------------------------------------------------------
sample_cols <- colnames(sv_annotated)[grepl("^Sample_", colnames(sv_annotated))]

cat("Number of sample columns:", length(sample_cols), "\n")

# ------------------------------------------------------------
# Step 4: Convert to long genotype format
# ------------------------------------------------------------
sv_long <- sv_annotated %>%
  pivot_longer(
    cols = all_of(sample_cols),
    names_to = "sample",
    values_to = "GT"
  )

# ------------------------------------------------------------
# Step 5: Convert genotypes to carrier / non-carrier status
# Carrier = genotype contains at least one ALT allele
# ------------------------------------------------------------
sv_long <- sv_long %>%
  mutate(
    present = case_when(
      GT %in% c("0/1", "1/0", "1/1") ~ 1L,
      TRUE ~ 0L
    )
  )

# ------------------------------------------------------------
# Step 6: Count SVs per sample by SV type
# ------------------------------------------------------------
sv_counts <- sv_long %>%
  filter(present == 1) %>%
  group_by(sample, SVTYPE) %>%
  summarise(count = n(), .groups = "drop") %>%
  mutate(sample = str_remove(sample, "^Sample_"))

cat("Summary of per-sample SV counts:\n")
print(summary(sv_counts$count))

# ------------------------------------------------------------
# Plot 1: Number of SVs per sample
# ------------------------------------------------------------
p_sample_counts <- ggplot(sv_counts, aes(x = reorder(sample, count), y = count, fill = SVTYPE)) +
  geom_bar(stat = "identity", width = 0.8) +
  coord_flip() +
  scale_fill_manual(values = c("INS" = "#3C5488", "DEL" = "#4DBBD5")) +
  theme_bw() +
  labs(
    x = "Samples",
    y = "Number of structural variants",
    fill = "SV type"
  ) +
  theme(
    panel.grid.major.y = element_blank(),
    axis.text.y = element_text(size = 5)
  )

ggsave("Number_of_SVs_per_sample.pdf", plot = p_sample_counts, width = 9, height = 5)
ggsave("Number_of_SVs_per_sample.png", plot = p_sample_counts, width = 9, height = 5, dpi = 600)

# ------------------------------------------------------------
# Step 7: SV length distribution
# ------------------------------------------------------------
sv_annotated <- sv_annotated %>%
  mutate(SV_kb = abs(SVLEN) / 1000)

p_sv_length <- ggplot(sv_annotated, aes(x = SV_kb, fill = SVTYPE)) +
  geom_histogram(
    bins = 25,
    color = "white",
    linewidth = 0.3
  ) +
  facet_wrap(
    ~SVTYPE,
    scales = "free",
    labeller = as_labeller(c(DEL = "Deletion", INS = "Insertion"))
  ) +
  scale_fill_manual(values = c("INS" = "#5470C6", "DEL" = "#4DBBD5")) +
  labs(
    x = "SV length (kb)",
    y = "Number of SVs"
  ) +
  theme_classic() +
  theme(
    legend.position = "none",
    strip.background = element_blank(),
    strip.text = element_text(size = 13),
    axis.text = element_text(size = 11),
    axis.title = element_text(size = 13)
  )

ggsave("SV_length_distribution.pdf", plot = p_sv_length, width = 9, height = 5)
ggsave("SV_length_distribution.png", plot = p_sv_length, width = 9, height = 5, dpi = 600)

# ------------------------------------------------------------
# Step 8: Global allele frequency (AF)
# ------------------------------------------------------------
sv_af <- sv_annotated %>%
  select(ID, SVTYPE, all_of(sample_cols)) %>%
  pivot_longer(
    cols = all_of(sample_cols),
    names_to = "sample",
    values_to = "GT"
  ) %>%
  mutate(
    GT = str_extract(GT, "^[0-9./]+"),
    allele_count = case_when(
      GT == "0/0" ~ 0,
      GT %in% c("0/1", "1/0") ~ 1,
      GT == "1/1" ~ 2,
      TRUE ~ NA_real_
    )
  ) %>%
  group_by(ID, SVTYPE) %>%
  summarise(
    AC = sum(allele_count, na.rm = TRUE),
    AN = sum(!is.na(allele_count)) * 2,
    AF = AC / AN,
    .groups = "drop"
  ) %>%
  filter(AN > 0, !is.na(AF))

p_af <- ggplot(sv_af, aes(x = AF)) +
  geom_histogram(
    bins = 40,
    fill = "#4DBBD5",
    color = "white"
  ) +
  labs(
    x = "Allele frequency",
    y = "Number of structural variants"
  ) +
  theme_classic() +
  theme(
    axis.text = element_text(size = 11),
    axis.title = element_text(size = 13),
    panel.border = element_rect(colour = "grey40", fill = NA, linewidth = 0.5)
  )

ggsave("SV_allele_frequency_distribution.pdf", plot = p_af, width = 7, height = 5)
ggsave("SV_allele_frequency_distribution.png", plot = p_af, width = 7, height = 5, dpi = 600)

# ------------------------------------------------------------
# Step 9: Global minor allele frequency (MAF)
# ------------------------------------------------------------
sv_maf <- sv_annotated %>%
  select(ID, SVTYPE, all_of(sample_cols)) %>%
  pivot_longer(
    cols = all_of(sample_cols),
    names_to = "sample",
    values_to = "GT"
  ) %>%
  mutate(
    GT = str_extract(GT, "^[0-9./]+"),
    allele_count = case_when(
      GT == "0/0" ~ 0,
      GT %in% c("0/1", "1/0") ~ 1,
      GT == "1/1" ~ 2,
      TRUE ~ NA_real_
    )
  ) %>%
  group_by(ID, SVTYPE) %>%
  summarise(
    AC = sum(allele_count, na.rm = TRUE),
    AN = sum(!is.na(allele_count)) * 2,
    AF = AC / AN,
    MAF = pmin(AF, 1 - AF),
    .groups = "drop"
  ) %>%
  filter(AN > 0, !is.na(MAF))

cat("Summary of MAF:\n")
print(summary(sv_maf$MAF))

p_maf <- ggplot(sv_maf, aes(x = MAF, fill = SVTYPE)) +
  geom_histogram(
    bins = 40,
    color = "white",
    alpha = 0.9
  ) +
  scale_fill_manual(
    values = c("DEL" = "#4DBBD5", "INS" = "#5470C6"),
    labels = c("DEL" = "Deletion", "INS" = "Insertion")
  ) +
  labs(
    x = "Minor allele frequency (MAF)",
    y = "Number of structural variants"
  ) +
  theme_classic() +
  theme(
    legend.title = element_blank(),
    legend.position = "top",
    axis.text = element_text(size = 11),
    axis.title = element_text(size = 13),
    panel.border = element_rect(colour = "grey40", fill = NA, linewidth = 0.5)
  )

ggsave("SV_minor_allele_frequency_distribution.pdf", plot = p_maf, width = 7, height = 5)
ggsave("SV_minor_allele_frequency_distribution.png", plot = p_maf, width = 7, height = 5, dpi = 600)

cat("03_graph_sv_summary_plots.R completed successfully.\n")
