#!/usr/bin/env Rscript

# ============================================================
# 06_graph_sv_population_upset.R
#
# Purpose:
#   Generate an UpSet plot of structural variant sharing among
#   populations from a graph-based SV genotype table 
#
# Input:
#   graph_sv_table.tsv
#   sample_population.tsv
#
# Output:
#   SV_population_upset.png
#   SV_population_upset.pdf
#   Population_specific_SV_counts.tsv
#   SVs_unique_to_<population>.tsv
#   SVs_shared_by_all_populations.tsv
#   SV_sharing_summary.tsv
#   SV_population_sharing_patterns.tsv
#   SV_exact_overlap_counts.tsv
#
# Input preparation:
#   bcftools query -H -f '%CHROM\t%POS\t%ID\t%REF\t%ALT[\t%GT]\n' \
#     salix_graph_75samples.merged.PASS.SV50.vcf.gz > graph_sv_table.tsv
#
# Notes:
#   - SV type and approximate SV length are inferred from REF and
#     ALT allele lengths because the graph-based VCF may lack
#     standard SVTYPE/SVLEN INFO fields.
# ============================================================

required_pkgs <- c("tidyverse", "UpSetR")
missing_pkgs <- required_pkgs[!required_pkgs %in% installed.packages()[, "Package"]]

if (length(missing_pkgs) > 0) {
  stop(
    paste(
      "Missing required packages:",
      paste(missing_pkgs, collapse = ", "),
      "\nPlease install them before running this script."
    )
  )
}

suppressPackageStartupMessages({
  library(tidyverse)
  library(UpSetR)
})

# ------------------------------------------------------------
# Input files
# ------------------------------------------------------------
sv_table_file <- "graph_sv_table.tsv"
population_file <- "sample_population.tsv"

# ------------------------------------------------------------
# Population settings
# ------------------------------------------------------------
expected_pops <- c("SW", "UK", "R", "E", "WE", "Br")

population_labels <- c(
  "SW" = "Sweden",
  "UK" = "UK",
  "R"  = "Russia",
  "E"  = "Eastern Europe",
  "WE" = "Western Europe",
  "Br" = "Breeding populations"
)

# ------------------------------------------------------------
# Step 1: Read graph-based SV genotype table
# ------------------------------------------------------------
sv_raw <- read_tsv(sv_table_file, show_col_types = FALSE)

# Clean sample column names generated by bcftools query
colnames(sv_raw) <- colnames(sv_raw) |>
  gsub("^#\\[[0-9]+\\]", "", x = _) |>
  gsub("^\\[[0-9]+\\]", "", x = _) |>
  gsub(":GT$", "", x = _)

# ------------------------------------------------------------
# Step 2: Infer approximate SV length and SV type
# ------------------------------------------------------------
sv_annotated <- sv_raw %>%
  mutate(
    ref_len = nchar(REF),
    alt_len = nchar(ALT),
    SVLEN = alt_len - ref_len,
    SVTYPE = case_when(
      SVLEN > 0 ~ "INS",
      SVLEN < 0 ~ "DEL",
      TRUE ~ "OTHER"
    )
  )

cat("Number of input variants:", nrow(sv_raw), "\n")
cat("Number of annotated variants:", nrow(sv_annotated), "\n")
cat("SV type counts:\n")
print(table(sv_annotated$SVTYPE, useNA = "ifany"))
cat("Summary of absolute inferred SV length:\n")
print(summary(abs(sv_annotated$SVLEN)))

# ------------------------------------------------------------
# Step 3: Identify sample genotype columns
# ------------------------------------------------------------
sample_cols <- colnames(sv_annotated)[str_detect(colnames(sv_annotated), "^Sample_")]

cat("Number of sample columns:", length(sample_cols), "\n")
print(head(sample_cols))
print(tail(sample_cols))

# ------------------------------------------------------------
# Step 4: Convert to long format
# ------------------------------------------------------------
sv_long <- sv_annotated %>%
  pivot_longer(
    cols = all_of(sample_cols),
    names_to = "sample",
    values_to = "GT"
  )

# Convert genotype to carrier / non-carrier
sv_long <- sv_long %>%
  mutate(
    present = case_when(
      GT %in% c("0/1", "1/0", "1/1") ~ 1L,
      TRUE ~ 0L
    )
  )

cat("Genotype counts:\n")
print(table(sv_long$GT, useNA = "ifany"))
cat("Carrier status counts:\n")
print(table(sv_long$present, useNA = "ifany"))

# ------------------------------------------------------------
# Step 5: Clean sample names and create unique SV IDs
# ------------------------------------------------------------
sv_long <- sv_long %>%
  mutate(
    sample = str_remove(sample, "^Sample_"),
    SV_ID = paste(CHROM, POS, REF, ALT, sep = "_")
  )

# ------------------------------------------------------------
# Step 6: Read population metadata
# ------------------------------------------------------------
population_df <- read_tsv(population_file, show_col_types = FALSE) %>%
  mutate(sample = as.character(sample))

cat("Population metadata preview:\n")
print(head(population_df))

# ------------------------------------------------------------
# Step 7: Merge SV data with population metadata
# ------------------------------------------------------------
sv_long_pop <- sv_long %>%
  left_join(population_df, by = "sample")

cat("Samples in SV table not matching population file:\n")
print(setdiff(unique(sv_long$sample), population_df$sample))

cat("Samples in population file not found in SV table:\n")
print(setdiff(population_df$sample, unique(sv_long$sample)))

cat("Population counts after merge:\n")
print(table(sv_long_pop$population, useNA = "ifany"))

# ------------------------------------------------------------
# Step 8: Keep only present SVs
# ------------------------------------------------------------
sv_present <- sv_long_pop %>%
  filter(present == 1)

# ------------------------------------------------------------
# Step 9: Keep one row per SV-population combination
# ------------------------------------------------------------
sv_pop_presence <- sv_present %>%
  distinct(SV_ID, population)

cat("SV-population presence preview:\n")
print(head(sv_pop_presence))

# ------------------------------------------------------------
# Step 10: Build binary matrix for UpSet plot
# ------------------------------------------------------------
sv_matrix <- sv_pop_presence %>%
  mutate(value = 1L) %>%
  pivot_wider(
    names_from = population,
    values_from = value,
    values_fill = 0
  )

# Add missing population columns if any are absent
for (p in expected_pops) {
  if (!p %in% colnames(sv_matrix)) {
    sv_matrix[[p]] <- 0L
  }
}

sv_matrix <- sv_matrix %>%
  select(SV_ID, all_of(expected_pops))

cat("Binary matrix dimensions:\n")
print(dim(sv_matrix))
print(head(sv_matrix))

# ------------------------------------------------------------
# Step 11: Prepare matrix for UpSetR
# ------------------------------------------------------------
sv_matrix_df <- sv_matrix %>%
  select(all_of(expected_pops)) %>%
  as.data.frame()

colnames(sv_matrix_df) <- unname(population_labels[expected_pops])

# ------------------------------------------------------------
# Step 12: Draw and save UpSet plot
# ------------------------------------------------------------
upset(
  sv_matrix_df,
  nsets = 6,
  nintersects = 40,
  order.by = "freq",
  keep.order = TRUE,
  main.bar.color = "#3C5488",
  sets.bar.color = "#4DBBD5",
  mainbar.y.label = "Number of shared SVs",
  sets.x.label = "Total SVs per population",
  text.scale = c(1.5, 1.5, 1.3, 1.3, 1.3, 1.3)
)

png(
  "SV_population_upset.png",
  width = 6000,
  height = 2400,
  res = 400
)

upset(
  sv_matrix_df,
  nsets = 6,
  nintersects = 40,
  order.by = "freq",
  keep.order = TRUE,
  main.bar.color = "#3C5488",
  sets.bar.color = "#4DBBD5",
  mainbar.y.label = "Number of shared SVs",
  sets.x.label = "Total SVs per population",
  text.scale = c(1.5, 1.5, 1.3, 1.3, 1.3, 1.3)
)

dev.off()

pdf(
  "SV_population_upset.pdf",
  width = 12,
  height = 7
)

upset(
  sv_matrix_df,
  nsets = 6,
  nintersects = 40,
  order.by = "freq",
  keep.order = TRUE,
  main.bar.color = "#3C5488",
  sets.bar.color = "#4DBBD5",
  mainbar.y.label = "Number of shared SVs",
  sets.x.label = "Total SVs per population",
  text.scale = c(1.5, 1.5, 1.3, 1.3, 1.3, 1.3)
)

dev.off()

# ------------------------------------------------------------
# Step 13: Count population-specific SVs
# ------------------------------------------------------------
sv_unique <- sv_matrix %>%
  filter(rowSums(select(., all_of(expected_pops))) == 1)

unique_counts <- colSums(select(sv_unique, all_of(expected_pops)))

unique_counts_df <- tibble(
  population = names(unique_counts),
  unique_SVs = as.integer(unique_counts)
) %>%
  mutate(population_label = unname(population_labels[population])) %>%
  select(population, population_label, unique_SVs)

print(unique_counts_df)

write_tsv(unique_counts_df, "Population_specific_SV_counts.tsv")

# ------------------------------------------------------------
# Step 14: Export population-specific SV lists
# ------------------------------------------------------------
for (p in expected_pops) {
  tmp <- sv_unique %>%
    filter(.data[[p]] == 1) %>%
    select(SV_ID)
  
  write_tsv(tmp, paste0("SVs_unique_to_", p, ".tsv"))
}

# ------------------------------------------------------------
# Step 15: Count SVs shared by all populations
# ------------------------------------------------------------
sv_shared_all <- sv_matrix %>%
  filter(rowSums(select(., all_of(expected_pops))) == length(expected_pops))

cat("Number of SVs shared by all populations:", nrow(sv_shared_all), "\n")

write_tsv(sv_shared_all, "SVs_shared_by_all_populations.tsv")

# ------------------------------------------------------------
# Step 16: Count SVs shared by exactly 1, 2, 3, 4, 5, or 6
# populations
# ------------------------------------------------------------
shared_summary <- sv_matrix %>%
  mutate(n_populations = rowSums(select(., all_of(expected_pops)))) %>%
  count(n_populations, name = "n_SVs")

print(shared_summary)

write_tsv(shared_summary, "SV_sharing_summary.tsv")

# ------------------------------------------------------------
# Step 17: Export complete sharing pattern table
# ------------------------------------------------------------
sv_patterns <- sv_matrix %>%
  mutate(
    n_populations = rowSums(select(., all_of(expected_pops))),
    sharing_pattern = apply(select(., all_of(expected_pops)), 1, function(x) {
      paste(expected_pops[as.logical(x)], collapse = ";")
    })
  )

write_tsv(sv_patterns, "SV_population_sharing_patterns.tsv")

# ------------------------------------------------------------
# Step 18: Count each exact overlap combination
# ------------------------------------------------------------
pattern_counts <- sv_patterns %>%
  count(sharing_pattern, sort = TRUE, name = "n_SVs")

print(pattern_counts)

write_tsv(pattern_counts, "SV_exact_overlap_counts.tsv")

cat("06_graph_sv_population_upset.R completed successfully.\n")
